name: mEvents
version: ${project.version}
main: mEvents.blockstock.mEvents.mEvents
api-version: '1.20'
authors: [ musbabaff ]
softdepend: [PlaceholderAPI, LuckPerms, WorldGuard, MythicMobs]
description: v2.0
website: musbabaff.com
commands:
  mevents:
    description: Main management command for mEvents.
    usage: /mevents <reload|fspawn|spawn>
    permission: mevents.admin
