name: mEvents
version: ${project.version}
main: mEvents.blockstock.mEvents.mEvents
api-version: '1.20'
authors: [ musbabaff ]
softdepend: [PlaceholderAPI, LuckPerms, WorldGuard, MythicMobs]
description: v2.0
website: musbabaff.com
commands:
<<<<<<< HEAD
  mevents:
=======
  kevents:
>>>>>>> 6980b04572758a8d0c0a02454a761566aab5661d
    description: Main management command for kEvents.
    usage: /mevents <reload|fspawn|spawn>
    permission: mevents.admin